// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjkXmaWsvBs4rgC17l0H3xyDhtopmM6k',
    appId: '1:869689967447:web:c0b6336ba0dce299feb412',
    messagingSenderId: '869689967447',
    projectId: 'realtime-gps-database',
    authDomain: 'realtime-gps-database.firebaseapp.com',
    databaseURL: 'https://realtime-gps-database-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-gps-database.appspot.com',
    measurementId: 'G-BFKWX41HNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxtqL8FfLLEDJSL3Q8580LXve9exRg-wU',
    appId: '1:869689967447:android:2342a6b494e675cbfeb412',
    messagingSenderId: '869689967447',
    projectId: 'realtime-gps-database',
    databaseURL: 'https://realtime-gps-database-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-gps-database.appspot.com',
  );
}
